
// Objective-C API for talking to the following Go packages
//
//	github.com/rxtech-lab/argo-trading/pkg/swift-argo
//
// File is generated by gomobile bind. Do not edit.
#ifndef __ArgoTrading_FRAMEWORK_H__
#define __ArgoTrading_FRAMEWORK_H__

#include "Swiftargo.objc.h"
#include "Universe.objc.h"

#endif
