// Objective-C API for talking to github.com/rxtech-lab/argo-trading/pkg/swift-argo Go package.
//   gobind -lang=objc github.com/rxtech-lab/argo-trading/pkg/swift-argo
//
// File is generated by gobind. Do not edit.

#ifndef __Swiftargo_H__
#define __Swiftargo_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class SwiftargoArgo;
@class SwiftargoMarketDownloader;
@protocol SwiftargoMarketDownloaderHelper;
@class SwiftargoMarketDownloaderHelper;

@protocol SwiftargoMarketDownloaderHelper <NSObject>
- (void)onDownloadProgress:(double)current total:(double)total message:(NSString* _Nullable)message;
@end

@interface SwiftargoArgo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
- (void)run;
- (void)setConfigPath:(NSString* _Nullable)path;
- (void)setDataPath:(NSString* _Nullable)path;
@end

@interface SwiftargoMarketDownloader : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(id<SwiftargoMarketDownloaderHelper> _Nullable)helper provider:(NSString* _Nullable)provider writer:(NSString* _Nullable)writer dataFolder:(NSString* _Nullable)dataFolder polygonApiKey:(NSString* _Nullable)polygonApiKey;
- (BOOL)download:(NSString* _Nullable)ticker from:(NSString* _Nullable)from to:(NSString* _Nullable)to interval:(NSString* _Nullable)interval error:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT SwiftargoArgo* _Nullable SwiftargoNewArgo(void);

FOUNDATION_EXPORT SwiftargoMarketDownloader* _Nullable SwiftargoNewMarketDownloader(id<SwiftargoMarketDownloaderHelper> _Nullable helper, NSString* _Nullable provider, NSString* _Nullable writer, NSString* _Nullable dataFolder, NSString* _Nullable polygonApiKey);

@class SwiftargoMarketDownloaderHelper;

@interface SwiftargoMarketDownloaderHelper : NSObject <goSeqRefInterface, SwiftargoMarketDownloaderHelper> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onDownloadProgress:(double)current total:(double)total message:(NSString* _Nullable)message;
@end

#endif
